modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Lykrast/MysticalWildlife/issues"

[[mods]]
modId="mysticalwildlife"
version="${version}"
displayName="Mystical Wildlife"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mystical-wildlife"
credits="The Minecraft Mod Development Discord for help."
authors="Lykrast"
description='''
Adds various imaginary animals to the world.
'''

[[dependencies.mysticalwildlife]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.voyage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"