modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/Lykrast/MysticalWildlife/issues"
[[mods]]
modId="mysticalwildlife"
version="${version}"
displayName="Mystical Wildlife"
displayURL="https://minecraft.curseforge.com/projects/mystical-wildlife"
#logoFile="examplemod.png"
credits="The Minecraft Mod Development Discord for help."
authors="Lykrast"
description='''
Adds various imaginary animals to the world.
'''
[[dependencies.mysticalwildlife]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mysticalwildlife]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"